### ISSUE TITLE
Brightness controls don't work in Windows when using BootChamp

### ISSUE THREAD

**Issue by samsoul1485** [kainjow/BootChamp#16]
Hello there

I have a early 2011 MacBook Pro with OS X 10.9.5. I use Windows 7 through Boot Camp 5.1.5621.

I have noticed that when I boot into Windows using Boot Champ 1.6.3, the brightness keys don't change my screen brightness. When I press F1 or F2 to increase/decrease the brightness, the brightness HUD does show up and increase/decrease, but the actual brightness of the screen doesn't change.

When I boot into Windows without using Boot Champ (I mean booting with the alt key pressed to launch the boot manager), the brightness controls work fine.

I have tested this several times and can reproduce the problem every time.

However, I am not a developer, so if there is anything I can do to help you with this issue, please tell me so :)

**Comment by kainjow** [comment]
I am aware of this issue but actually haven't heard about it for a while now, so I think it is an issue limited to older systems, most likely a bug in the firmware. Unfortunately I don't know of any workarounds except for just not using BootChamp.

**Comment by dotnetwise** [comment]
still not working on sep 2017 with w10 creative update
