### ISSUE TITLE
EFI disk not found when not first partition

### ISSUE THREAD

**Issue by kainjow** [kainjow/BootChamp#17]
Originally from https://github.com/kainjow/BootChamp/issues/8#issuecomment-120633311

EFI partition is second partition, not first, and BootChamp is looking only at the first partition.

**Comment by kainjow** [comment]
@SuperSirLink here is a test build. Can you give it a try?

http://kainjow.com/downloads/BootChamp17b.zip

**Comment by SuperSirLink** [comment]
Thanks Kevin for you work on this... Testing it now!

**Comment by SuperSirLink** [comment]
Works perfectly!!  Thanks so much!

**Comment by kainjow** [comment]
Great, thanks for testing! I'll be posting the official new 1.7 version soon.

**Comment by SuperSirLink** [comment]
Happy to be of assistance and thanks again for working on this... You don't realize how much you miss the little things till they don't work. :)  Not afraid of applying the terminal commands each time, but having Bootchamp is just too convenient... :)
