### ISSUE TITLE
Bless failed.

### ISSUE THREAD

**Issue by danihungary** [kainjow/BootChamp#18]
I saw there was an issue with that, and solved, but recently my Boot Champ started to give me bless failed message. Tried to remove my NTFS driver, tried basically everything, but no solution.

**Comment by kainjow** [comment]
Was there additional information in the error dialog?

**Comment by danihungary** [comment]
![image](https://cloud.githubusercontent.com/assets/13887029/9396376/d6535112-4794-11e5-984e-fffe20f09c2e.png)
Right I am sorry. This is what I got. If I can provide any log, I will, I'm just not familiar with Boot Champ, neither with GitHub (yet) Just tell me what to do, and what data you need. :)

**Comment by kainjow** [comment]
Are you running version 1.7?

**Comment by danihungary** [comment]
Yup, I downloaded it straight from Your website. :)

**Comment by kainjow** [comment]
Can you email me the logs at ~/Library/Application Support/BootChamp/Logs ?

**Comment by danihungary** [comment]
The only file there is BOHelper (checked the hidden ones too) Is it what you need? Or is logs turned off and I need to turn it on somehow?

**Comment by kainjow** [comment]
I think that is the system-level library. The one I'm looking for is in your Users folder. In Finder, go to the Go menu then select Go to Folder. Paste in this exactly:

    ~/Library/Application Support/BootChamp/Logs

Then click Go. Finder should open this location and there should be text files in it.

**Comment by danihungary** [comment]
emailed them through your website. :)

**Comment by kainjow** [comment]
Did you do a major Windows update recently? Does your Windows volume show in Startup Disk in System Preferences?

**Comment by kainjow** [comment]
I put up a [test build](http://kainjow.com/downloads/BootChamp_1.7.1_test1.zip). Can you run this command first and then try that build?

    defaults write com.kainjow.BootChamp NoLegacy -bool YES

**Comment by danihungary** [comment]
No I did not have any update, I dont update my Windows at all. Though I cannot see it in Sys Preferences. When I hold opt on start, I see it, but in Sys Pref I dont. I tried the test build, it restarts into OS X.

**Comment by Mudflapper** [comment]
My Windows partition does appear in System Prefs.

I ran that command then tried your new Boot Champ test build but it errored out again:

--

BootChamp was unable to set your Windows volume as the temporary startup disk

Bless failed:

EFI found at IODeviceTree:/efi
Mount point for /Volumes/BOOTCAMP is /Volumes/BOOTCAMP
Mount point is '/Volumes/BOOTCAMP'
No BootX creation requested
No boot.efi creation requested
found ioreg "FirmwareFeaturesMask"; featureMaskValue=0xC003FF37
found ioreg "FirmwareFeatures"; featureFlagsValue=0xC001F537
isPreBootEnvironmentUEFIWindowsBootCapable=0
preboot environment is not UEFI boot capable
isDVDWithElToritoWithUEFIBootableOS=0
Checking if disk is complex (if it is associated with booter partitions)
GPT detected
Booter partition required at index 5
System partition found
Preferred system partition found: disk0s1
Returning booter information dictionary:
<CFBasicHash 0x7fedbbd00200 [0x7fff73104890]>{type = mutable dict, count = 3,
entries =>
	0 : <CFString 0x103ba0990 [0x7fff73104890]>{contents = "System Partitions"} = (
    disk0s1
)
	1 : <CFString 0x103ba1170 [0x7fff73104890]>{contents = "Data Partitions"} = (
    disk0s4
)
	2 : <CFString 0x103ba1190 [0x7fff73104890]>{contents = "Auxiliary Partitions"} = (
)
}

Path to mountpoint given: /Volumes/BOOTCAMP
IOMedia disk0s4 has UUID 088795F8-5F77-431B-BE89-A3F6C56A74D8
Setting EFI NVRAM:
	efi-boot-next='<array><dict><key>IOMatch</key><dict><key>IOProviderClass</key><string>IOMedia</string><key>IOPropertyMatch</key><dict><key>UUID</key><string>088795F8-5F77-431B-BE89-A3F6C56A74D8</string></dict></dict><key>BLLastBSDName</key><string>disk0s4</string></dict></array>'
Could not set boot device property: 0xe00002bc

**Comment by kainjow** [comment]
@Mudflapper this build tries to address a specific issue @danihungary is seeing. I think you might be having the issue with the latest El Capitan beta? See issue #19.

**Comment by kainjow** [comment]
@danihungary interesting, so it doesn't give an error, but doesn't boot into Windows.

I think something is off with your Boot Camp setup. Usually if the Windows partition doesn't show up in Startup Disk, then there is a configuration problem. BootChamp expects Boot Camp to be working properly. So at this point I don't really know what is the issue, or what else to check.

**Comment by danihungary** [comment]
Thank You for all the help! So the fault is at different place, I'll try to figure it out. :) Thank You though again for all the effort, I hope I can use BootChamp soon again. :+1:
