### ISSUE TITLE
Still not booting into Bootcamp

### ISSUE THREAD

**Issue by rokeno** [kainjow/BootChamp#20]
Hi, 
i'm using Windows 8.1 and Mac OS X 10.11.2 beta testing and i can't reach Windows volume through bootchamp.
error "BootChamp was unable to set your Windows volume as the temporary startup disk. Bless failed: ...." and allot of errors that i cannot copy and i don't know where the logs are stored.
It states that EFI is found at IODeviceTree:/efi... etc etc..

Any ideas or help you, guys, can give me?

Thanks.

**Comment by rokeno** [comment]
![screen shot 2015-11-15 at 8 27 16 pm](https://cloud.githubusercontent.com/assets/10266176/11170254/4f5dee10-8bd7-11e5-8558-df57b0eb7216.png)

**Comment by kainjow** [comment]
Hi, please see this: http://kainjow.tumblr.com/post/128933657269/bootchamp-and-el-capitan

**Comment by rokeno** [comment]
Thank. Worked.

**Comment by rokeno** [comment]
reply@reply.github.com

The user with the email rokenom@gmail.com has sent you an invitation
to join MEGA.

""

Join rokenom@gmail.com on MEGA by clicking below:

https://mega.nz/#newsignupcmVwbHkrMDA5Y2E2NDBiNDY5OWYyY2I4ZDEzMjE4Y2Y2MzA4MDMxYTc1OWNhYzg3YjkxMDNkOTJjZjAwMDAwMDAxMTI2MGRiOTU5MmExNjljZTA2Zjk2YzY4QHJlcGx5LmdpdGh1Yi5jb21n3GO6_9VwBQ

Best regards,
— Team MEGA
