### ISSUE TITLE
[Don't] reopen windows on restart

### ISSUE THREAD

**Issue by isaacl** [kainjow/BootChamp#21]
The OS X restart dialog has an option "Reopen windows when logging back in".

It'd be great if BootChamp provided this choice as a preference. I turn the feature off for normal reboots, but there's currently no way to disable it for BootChamp.

**Comment by kainjow** [comment]
In the BootChamp menu there is Preferences > Launch at startup - you can uncheck that to disable it. If you don't see that make sure you are on the latest version.

**Comment by isaacl** [comment]
Oh. I assumed that was about starting boot champ at login...

**Comment by kainjow** [comment]
Ah, I think you're referring to the restorability feature of OS X. BootChamp's feature just determines whether it launches at login, it doesn't support restorability.

Since BC no longer works with 10.11 I don't have any further plans to update the app.
