### ISSUE TITLE
Bless failed

### ISSUE THREAD

**Issue by olsenlid** [kainjow/BootChamp#22]
Bless failed:

EFI found at IODeviceTree:/efi
found ioreg "FirmwareFeaturesMask"; featureMaskValue=0xC000FFFF
found ioreg "FirmwareFeatures"; featureFlagsValue=0xC0005403
isPreBootEnvironmentUEFIWindowsBootCapable=0
preboot environment is not UEFI boot capable
isDVDWithElToritoWithUEFIBootableOS=0
Checking if disk is complex (if it is associated with booter partitions)
GPT detected
Booter partition required at index 2
System partition found
Preferred system partition found: disk2s1
Returning booter information dictionary:
<CFBasicHash 0x7fd741c0c920 [0x7fff79e1d440]>{type = mutable dict, count = 3,
entries =>
    0 : <CFString 0x10c7ed990 [0x7fff79e1d440]>{contents = "System Partitions"} = (
    disk2s1,
    disk0s1
)
    1 : <CFString 0x10c7ee170 [0x7fff79e1d440]>{contents = "Data Partitions"} = (
    disk0s1
)
    2 : <CFString 0x10c7ee190 [0x7fff79e1d440]>{contents = "Auxiliary Partitions"} = (
)
}

IOMedia disk0s1 has UUID 8C4EB2B0-2F96-44FE-8F71-0EB2C42B2C11
Setting EFI NVRAM:
    efi-boot-next='<array><dict><key>IOMatch</key><dict><key>IOProviderClass</key><string>IOMedia</string><key>IOPropertyMatch</key><dict><key>UUID</key><string>8C4EB2B0-2F96-44FE-8F71-0EB2C42B2C11</string></dict></dict><key>BLLastBSDName</key><string>disk0s1</string></dict></array>'
Could not set boot device property: 0xe00002bc

**Comment by kainjow** [comment]
You're probably on El Capitan, which BootChamp is not compatible with: http://kainjow.tumblr.com/post/128933657269/bootchamp-and-el-capitan
