### ISSUE TITLE
No bootable device found

### ISSUE THREAD

**Issue by jameshigh** [kainjow/BootChamp#7]
This app is not working on my MacBook Air (2013 model) with Windows 8.1 installed. It just gives me an error after restart "No bootable device found. Press any key to restart." Booting into Windows works fine when choosing as startup disk in Mac OS or when holding down option key at startup.

**Comment by SuperSirLink** [comment]
Having this issue too, but don't think it is bootchamp.  If I choose the window partition from start disk and reboot I get the same message.  If I hold down the option key I don't see the windows volume just EFI boot, choosing that successfully boots to Windows...
